import unreal
MAX_ATTEMPTS = 50
VISIBILITY_TRACE_RADIUS = 10.0
CAMERA_HEIGHT = 500
FAR_DISTANCE = 5.0
DEBUG_TACE=unreal.DrawDebugTrace.NONE
SEARCH_SPACE = 200
STATIC_DISTANCE = 20
MAX_WALK_STRIDE_CM = 500.0